name: MongoDB Backup

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install MongoDB Database Tools
        run: |
          sudo apt-get update
          wget -qO - https://www.mongodb.org/static/pgp/server-8.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/8.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-database-tools

      - name: Dump MongoDB
        run: |
          TIMESTAMP=$(date +%Y-%m-%dT%H-%M-%S)
          BACKUP_FILE="backup-$TIMESTAMP.gz"
          echo "BACKUP_FILE=$BACKUP_FILE" >> $GITHUB_ENV
          mongodump --uri="$MONGO_URI" --gzip --archive="./$BACKUP_FILE"
          ls -lh .
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}

      - name: Send backup via email
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "MongoDB Backup ${{ env.BACKUP_FILE }}"
          to: ${{ secrets.EMAIL_USERNAME }}
          from: "GitHub Backup Bot <${{ secrets.EMAIL_USERNAME }}>"
          body: |
            MongoDB backup created successfully at ${{ env.BACKUP_FILE }}.
            Attached is your backup file.
          attachments: ${{ env.BACKUP_FILE }}

      - name: Delete local backup file
        run: |
          echo "Deleting local backup file: $BACKUP_FILE"
          rm -f "$BACKUP_FILE"
